Change dependency manager from Carthage to Cocoapods
Azure-Samples/active-directory-b2c-ios-swift-native-msal pull request #52
Opened 2021-04-08 17:20 UTC by mipetriu

The main focus of this PR is to change the dependency manager that installs MSAL in the iOS B2C sample from Carthage to Cocoapods. Carthage has been reported to not work very well on some people's machines, plus Cocoapods is used in other MSAL iOS samples as well, so this can keep the MSAL installation steps the same across code samples.

This PR also addresses a few instances of deprecated MSALWebviewParameters `initWithParentViewController` instances, as well as address a few references to that deprecated method in the ReadMe.

2021-05-27 22:38 UTC, oldalton approved these changes

2021-05-27 22:42 UTC, kaisong1990 approved these changes

2021-05-27 22:46 UTC, ameyapat requested changes

2021-05-27 22:46 UTC, ameyapat commented on Podfile.lock
> +  - MSAL (1.1.13):
Can this be updated to latest MSAL? Right now when I run pod install it seems to use MSAL 1.1.13

2021-05-27 22:46 UTC, ameyapat commented on README.md
> +    let kAuthorityHostName = "fabrikamb2c.b2clogin.com" // Your authority host name
When I click Authorize, it seems to open localhost instead of SUSI(login) page . Can you confirm?

2021-07-22 22:28 UTC, ameyapat commented on README.md
> +    let kAuthorityHostName = "fabrikamb2c.b2clogin.com" // Your authority host name
Reply URL was changed back to our client id in portal, should be alright now.

2021-09-29 23:32 UTC, ameyapat approved these changes

2021-09-30 00:00 UTC, merged